// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DingDongDelivey_Back.Database;

namespace DingDongDelivey_Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220715170454_v20")]
    partial class v20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DingDongDelivey_Back.Models.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("buyerId")
                        .HasColumnType("int");

                    b.Property<int>("deliverymanId")
                        .HasColumnType("int");

                    b.Property<bool>("isAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("isDelivered")
                        .HasColumnType("bit");

                    b.Property<string>("orderAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orderComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("orderPrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("timeTillDelivery")
                        .HasColumnType("datetime2");

                    b.HasKey("orderId");

                    b.HasIndex("buyerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            orderId = 1,
                            buyerId = 3,
                            deliverymanId = 2,
                            isAccepted = true,
                            isDelivered = false,
                            orderAddress = "Futoska 120",
                            orderComment = "",
                            orderPrice = 1110f,
                            timeTillDelivery = new DateTime(2022, 6, 8, 16, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            orderId = 2,
                            buyerId = 3,
                            deliverymanId = 2,
                            isAccepted = true,
                            isDelivered = true,
                            orderAddress = "Bulevar Oslobodjenja 220",
                            orderComment = "",
                            orderPrice = 930f,
                            timeTillDelivery = new DateTime(2022, 6, 1, 16, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            orderId = 3,
                            buyerId = 3,
                            deliverymanId = 2,
                            isAccepted = false,
                            isDelivered = false,
                            orderAddress = "Bulevar Oslobodjenja 220",
                            orderComment = "",
                            orderPrice = 930f,
                            timeTillDelivery = new DateTime(2022, 7, 13, 23, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<float>("quantity")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            ingredients = "Chicken, beans, rice, tomatoes, corn, red salsa, nacho",
                            isDeleted = false,
                            name = "Chicken Burrito",
                            price = 410f,
                            quantity = -1f
                        },
                        new
                        {
                            id = 2,
                            ingredients = "100% beef burger, bacon, letuce, tomatoes, onions, secret sauce",
                            isDeleted = false,
                            name = "Beef Burger",
                            price = 550f,
                            quantity = -1f
                        },
                        new
                        {
                            id = 3,
                            ingredients = "Tomato sauce, mozzarella, basil",
                            isDeleted = false,
                            name = "Pizza Margharita 24cm",
                            price = 320f,
                            quantity = -1f
                        },
                        new
                        {
                            id = 4,
                            ingredients = "Tomato sauce, mozzarella, basil",
                            isDeleted = false,
                            name = "Pizza Margharita 32cm",
                            price = 460f,
                            quantity = -1f
                        });
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.ProductOrder", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("ProductOrders");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            OrderId = 1,
                            ProductQuantity = 1
                        },
                        new
                        {
                            ProductId = 2,
                            OrderId = 1,
                            ProductQuantity = 2
                        },
                        new
                        {
                            ProductId = 3,
                            OrderId = 2,
                            ProductQuantity = 2
                        },
                        new
                        {
                            ProductId = 4,
                            OrderId = 2,
                            ProductQuantity = 2
                        },
                        new
                        {
                            ProductId = 3,
                            OrderId = 3,
                            ProductQuantity = 3
                        },
                        new
                        {
                            ProductId = 4,
                            OrderId = 3,
                            ProductQuantity = 1
                        });
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("deliveryS")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hasOrder")
                        .HasColumnType("bit");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userT")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            address = "Novi Sad",
                            dateOfBirth = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            deliveryS = 3,
                            email = "godlike.jovan@gmail.com",
                            firstName = "Jovan",
                            hasOrder = false,
                            image = "",
                            isActive = true,
                            isDeleted = false,
                            lastName = "Miljkovic",
                            password = "$2a$11$1XIsp3s1WkZ.vo1N.brTBurGfTYbdXGCL75zHeOUBvPl63deBEuDK",
                            userT = 0,
                            username = "AdminJovan"
                        },
                        new
                        {
                            userId = 2,
                            address = "Novi Sad",
                            dateOfBirth = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            deliveryS = 3,
                            email = "deliveryjovan@gmail.com",
                            firstName = "Jovan",
                            hasOrder = false,
                            image = "",
                            isActive = true,
                            isDeleted = false,
                            lastName = "Miljkovic",
                            password = "$2a$11$PBvQJgbEi/CXfyQwP0Fk5uw3RTh2GFHSrlkSQPX0SYtzNmu2mLRzi",
                            userT = 1,
                            username = "DeliveryJovan"
                        },
                        new
                        {
                            userId = 3,
                            address = "Novi Sad",
                            dateOfBirth = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            deliveryS = 3,
                            email = "buyerjovan@gmail.com",
                            firstName = "Jovan",
                            hasOrder = true,
                            image = "",
                            isActive = true,
                            isDeleted = false,
                            lastName = "Miljkovic",
                            password = "$2a$11$gDfV6g.B1FuCXmYRIUXEMOMXcurMn9TnBztYuJnp6KG7vnLVj6fOS",
                            userT = 2,
                            username = "BuyerJovan"
                        },
                        new
                        {
                            userId = 4,
                            address = "Novi Sad",
                            dateOfBirth = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            deliveryS = 3,
                            email = "deliveryjovan2@gmail.com",
                            firstName = "Jovan",
                            hasOrder = false,
                            image = "",
                            isActive = false,
                            isDeleted = false,
                            lastName = "Miljkovic",
                            password = "$2a$11$n1WIduSydY6J3frhcJWalugWpFvmyNh.IMijlxKJJ/uTNc7/ybpm6",
                            userT = 1,
                            username = "DeliveryJovan"
                        });
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.Order", b =>
                {
                    b.HasOne("DingDongDelivey_Back.Models.User", "buyer")
                        .WithMany("orders")
                        .HasForeignKey("buyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("buyer");
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.ProductOrder", b =>
                {
                    b.HasOne("DingDongDelivey_Back.Models.Order", "Order")
                        .WithMany("orderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DingDongDelivey_Back.Models.Product", "Product")
                        .WithMany("orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.Order", b =>
                {
                    b.Navigation("orderItems");
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.Product", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.User", b =>
                {
                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
