// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DingDongDelivey_Back.Database;

namespace DingDongDelivey_Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220706101451_v9")]
    partial class v9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("orderItemsid")
                        .HasColumnType("int");

                    b.Property<int>("ordersorderId")
                        .HasColumnType("int");

                    b.HasKey("orderItemsid", "ordersorderId");

                    b.HasIndex("ordersorderId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("buyerId")
                        .HasColumnType("int");

                    b.Property<bool>("isAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("isDelivered")
                        .HasColumnType("bit");

                    b.Property<string>("orderAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orderComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("orderPrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("timeTillDelivery")
                        .HasColumnType("datetime2");

                    b.HasKey("orderId");

                    b.HasIndex("buyerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<float>("quantity")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            ingredients = "Chicken, beans, rice, tomatoes, corn, red salsa, nacho",
                            isDeleted = false,
                            name = "Chicken Burrito",
                            price = 410f,
                            quantity = -1f
                        },
                        new
                        {
                            id = 2,
                            ingredients = "100% beef burger, bacon, letuce, tomatoes, onions, secret sauce",
                            isDeleted = false,
                            name = "Beef Burger",
                            price = 550f,
                            quantity = -1f
                        },
                        new
                        {
                            id = 3,
                            ingredients = "Tomato sauce, mozzarella, basil",
                            isDeleted = false,
                            name = "Pizza Margharita 24cm",
                            price = 320f,
                            quantity = -1f
                        },
                        new
                        {
                            id = 4,
                            ingredients = "Tomato sauce, mozzarella, basil",
                            isDeleted = false,
                            name = "Pizza Margharita 32cm",
                            price = 460f,
                            quantity = -1f
                        });
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("deliveryS")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hasOrder")
                        .HasColumnType("bit");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userT")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            address = "Novi Sad",
                            dateOfBirth = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            deliveryS = 3,
                            email = "godlike.jovan@gmail.com",
                            firstName = "Jovan",
                            hasOrder = false,
                            image = "",
                            isActive = true,
                            isDeleted = false,
                            lastName = "Miljkovic",
                            password = "jovan123",
                            userT = 0,
                            username = "AdminJovan"
                        },
                        new
                        {
                            userId = 2,
                            address = "Novi Sad",
                            dateOfBirth = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            deliveryS = 3,
                            email = "godlike.jovan@gmail.com",
                            firstName = "Jovan",
                            hasOrder = false,
                            image = "",
                            isActive = true,
                            isDeleted = false,
                            lastName = "Miljkovic",
                            password = "jovan123",
                            userT = 1,
                            username = "DeliveryJovan"
                        },
                        new
                        {
                            userId = 3,
                            address = "Novi Sad",
                            dateOfBirth = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            deliveryS = 3,
                            email = "godlike.jovan@gmail.com",
                            firstName = "Jovan",
                            hasOrder = false,
                            image = "",
                            isActive = true,
                            isDeleted = false,
                            lastName = "Miljkovic",
                            password = "jovan123",
                            userT = 2,
                            username = "BuyerJovan"
                        });
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("DingDongDelivey_Back.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("orderItemsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DingDongDelivey_Back.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("ordersorderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.Order", b =>
                {
                    b.HasOne("DingDongDelivey_Back.Models.User", "buyer")
                        .WithMany("orders")
                        .HasForeignKey("buyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("buyer");
                });

            modelBuilder.Entity("DingDongDelivey_Back.Models.User", b =>
                {
                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
